### ISSUE TITLE
Problem with AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by TomasTrnkaPLC** [kentaroy47/frcnn-from-scratch-with-keras#59]
Hi.
I have a problem. I generate a labels.csv 
E:/George/images/02.jpg,501,315,705,837,person 
but everytime i run `python train_rpn.py --network mobilenetv2 -o simple -p E:/George/images/labels.csv  `
then I get 
`: 0000:01:00.0, compute capability: 7.5)
Parsing annotation files
filename
Traceback (most recent call last):
  File "train_rpn.py", line 130, in <module>
    all_imgs, classes_count, class_mapping = get_data(options.train_path)
  File "E:\George\keras_frcnn\simple_parser.py", line 39, in get_data
    (rows, cols) = img.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'`

I try to change my labels.csv like /images/02.jpg or just 02.jpg but no sense can you please help me why that simple_parser.py cannot work?

**Comment by kentaroy47** [comment]
label file should be a `.txt` file, as in the original VOC.
can you fix that and try again?

**Comment by TomasTrnkaPLC** [comment]
My apologies. I made a mistake with my xml_to_csv. He generates the first row with column prefix like filename,x1,y2...
E:\images\01.jpg ....

csv or txt that does matter. Work with both.

**Comment by prinipj** [comment]
My label file is annotate.txt where the rows are like this drive/My Drive/Colab Notebooks/frcnn/dataset/1.jpg",251,161,598,335,pothole

When I run this command
!python 'drive/My Drive/Colab Notebooks/frcnn/frcnn-from-scratch-with-keras/train_rpn.py' --network resnet50 -o simple -p 'drive/My Drive/Colab Notebooks/frcnn/dataset/annotate.txt'

I get this error
Parsing annotation files
Traceback (most recent call last):
  File "drive/My Drive/Colab Notebooks/frcnn/frcnn-from-scratch-with-keras/train_rpn.py", line 130, in <module>
    all_imgs, classes_count, class_mapping = get_data(options.train_path)
  File "/content/drive/My Drive/Colab Notebooks/frcnn/frcnn-from-scratch-with-keras/keras_frcnn/simple_parser.py", line 37, in get_data
    (rows,cols) = img.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'

I have different solutions but I am unable to resolve

**Comment by SnehaDeepak** [comment]
I m also facing the same issue.
get_data not able to read images from path. therefore attribute error..
any solution to that...
